### ISSUE TITLE
OpenGlCbGetProcAddrFn

### ISSUE THREAD

**Issue by amrmons** [ninebysix/MooTube#4]
Got the same error on Mobian, Arch and Manjaro

Traceback (most recent call last):
  File "/usr/bin/mootube", line 33, in <module>
    sys.exit(load_entry_point('MooTube==1.3', 'console_scripts', 'mootube')())
  File "/usr/bin/mootube", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/MooTube-1.3-py3.10.egg/src/app.py", line 17, in <module>
    from src.utils.player import MediaPlayer
  File "/usr/lib/python3.10/site-packages/MooTube-1.3-py3.10.egg/src/utils/player.py", line 9, in <module>
    from mpv import MPV, MpvRenderContext, OpenGlCbGetProcAddrFn
ImportError: cannot import name 'OpenGlCbGetProcAddrFn' from 'mpv' (/usr/lib/python3.10/site-packages/python_mpv-1.0.1-py3.10.egg/mpv.py)

**Comment by jakeday** [comment]
This has been fixed.
